server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
#    url: jdbc:mysql:///leyou?serverTimezone=GMT
    url: jdbc:mysql://192.168.1.66:3306/leyou?serverTimezone=GMT&characterEncoding=utf8
    username: root
#    password: 66257191
    password: 123456
  rabbitmq:
    host: 192.168.1.66
    virtual-host: /leyou
    username: leyou
    password: leyou
    template:
      exchange: LEYOU.ITEM.EXCHANGE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.leyou.item.pojo
  configuration:
    map-underscore-to-camel-case: true
