server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://192.168.1.66:3306/leyou?serverTimezone=GMT&characterEncoding=utf8
    username: root
    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.1.66
  rabbitmq:
    host: 192.168.1.66
    virtual-host: /leyou
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

  mybatis:
    type-aliases-package: com.leyou.user.pojo