server:
  port: 10010
spring:
  application:
    name: leyou-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api # 所有路径携带api的都会自动转化成 没有api的
  routes:
    item-service: /item/**      # 路由到商品的微服务
    search-service: /search/**  # 路由到搜索的微服务
    user-service: /user/**      # 用户微服务
    auth-service: /auth/**      # 授权中心微服务
    cart-service: /cart/**
  add-host-header: true
  sensitive-headers: #覆盖默认敏感头信息
leyou:
  jwt:
    pubKeyPath: E:\\javaitem\\application\\leyou\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item