server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.1.66
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eurela
    registry-fetch-interval-seconds: 10
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5